---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LOAD LIBRARIES # 
```{r}
library(lmerTest)
library(emmeans)
library(sjPlot)
library(drc)
library(Rmisc)
library(ggplot2)
library(tidyr)
library(dplyr)
library(plyr)
library(reshape2)
library(data.table)
```

# IMPORT DATA #
```{r}
IPa <- readxl::read_xlsx("data/PAM/2021-06-08_Past-4temps-Inshore.xlsx")

OPa <- readxl::read_xlsx("data/PAM/2021-06-10_Past-4temps-Offshore.xlsx") %>%
  select(-Temp)

NAc <- readxl::read_xlsx("data/PAM/2021-06-11_Acer-4temps-MoteLooeNursery_Run2.xlsx") %>%
  mutate(TagNumber = Genotype,
         Comments = Comment) %>%
  select(-Comment)

# Combine all Datasets 
Allpam <- rbind(IPa, OPa, NAc) %>%
  mutate(Species = case_when(Species == "Acropora cervicornis" ~ "ACER",
                             Species == "Porites astreoides" ~ "PAST")) %>%
  select(TubeNumber, sample_ID = SampleName, species = Species, Geno = Genotype, Treatment, Temperature = Temp_Setpoint, Timepoint, FvFm = PAM) %>%
  mutate(TP_ID = case_when(grepl("T1", sample_ID) ~ "T1",
                           grepl("T2", sample_ID) ~ "T2",
                           grepl("T3", sample_ID) ~ "T3",
                           grepl("T4", sample_ID) ~ "T4",
                           grepl("T5", sample_ID) ~ "T5",
                           grepl("T0", sample_ID) ~ "T0",
                           grepl("TF", sample_ID) ~ "TF"))


Allpam$FacTemp<-as.factor(Allpam$Temperature)
Allpam$Geno<-as.factor(Allpam$Geno)
Allpam$Temperature<- as.integer(Allpam$Temperature)
Allpam<-as.data.frame(Allpam)

PAST <- Allpam %>%
  filter(species == "PAST")

ACER <- Allpam %>%
  filter(species == "ACER")
```

# PAST ED50s PER GENO PER TIMEPOINT #
```{r}
Past_TP <- PAST %>%
  filter(TP_ID == "T1" | TP_ID == "T2" | TP_ID == "T3" | TP_ID == "T4" & Timepoint == "T4" | TP_ID == "T5" & Timepoint == "T5") %>%
  mutate(ID = paste(Geno,TP_ID))

Past_TP_DRC <- drm(FvFm ~ Temperature, data = Past_TP, curveid = ID,
             fct = LL.3(names = c('hill', 'max', 'ed50')))

summary(Past_TP_DRC)
compParm(Past_TP_DRC, 'ed50')
compParm(Past_TP_DRC, 'ed50', "-")
plot(Past_TP_DRC)

Past_TP_ED <- ED(Past_TP_DRC, c(50), interval = "delta")

Past_ED_df <- as.data.frame(Past_TP_ED) %>%
  setDT(keep.rownames = "Geno") %>%
  mutate(Genotype = case_when(grepl(":01", Geno) ~ "01",
                              grepl(":02", Geno) ~ "02",
                              grepl(":03", Geno) ~ "03",
                              grepl(":04", Geno) ~ "04",
                              grepl(":05", Geno) ~ "05",
                              grepl(":06", Geno) ~ "06",
                              grepl(":07", Geno) ~ "07",
                              grepl(":08", Geno) ~ "08",
                              grepl(":09", Geno) ~ "09",
                              grepl(":10", Geno) ~ "10")) %>%
  mutate(TP_ID = case_when(grepl("T1", Geno)~ "T1",
                           grepl("T2", Geno)~ "T2",
                           grepl("T3", Geno)~ "T3",
                           grepl("T4", Geno)~ "T4",
                           grepl("T5", Geno)~ "T5")) %>%
select(-Geno, ED50 = Estimate) %>%
  mutate(site = case_when(Genotype == "01" | Genotype == "02" | Genotype == "03" | 
                            Genotype == "04" | Genotype == "05" ~ "offshore",
                          Genotype == "06" | Genotype == "07" | Genotype == "08" | 
                            Genotype == "09" | Genotype == "10" ~ "inshore"))

Past_ED50_TP <- Past_ED_df %>%
  select(Genotype, TP_ID, site, ED50)

Genotype <- Past_ED50_TP$Genotype

ggplot(Past_ED50_TP, aes(x = TP_ID, y = ED50, color = Genotype)) +
  geom_point() +
  ggrepel::geom_text_repel(label= Genotype, nudge_x = 0.25) +
  facet_wrap(~site) +
  theme_bw() +
  theme(legend.position = "none") 

ggsave(filename = "plots/Past_Rank_ED50_all_TP_genofits.png", width = 174, height = 100, units = "mm")

  
geno_ED50s_TP <- Past_ED50_TP %>%
  spread(key = TP_ID, value = ED50) %>%
  group_by(Genotype) %>%
  mutate(avgfit = mean(c(T1, T2, T3, T4, T5)),
         min = min(c(T1, T2, T3, T4, T5)),
         max = max(c(T1, T2, T3, T4, T5)),
         diff = max - min) 

library("writexl")
geno_ED50s_TP %>%
  write_xlsx("ED50/Past_all_TPs_Genets_ED50.xlsx")

```

# PAST ED50S PER GENO PER T3 SAMPLING TIMEPOINT (T3, T4, & T5 SAMPLES FROM T3) #
```{r}
T3_Past <- PAST %>%
  filter(Timepoint == "T3")%>%
  mutate(ID = paste(Geno,TP_ID))

Past_T3_DRC <- drm(FvFm ~ Temperature, data = T3_Past, curveid = ID,
             fct = LL.3(names = c('hill', 'max', 'ed50')))

summary(Past_T3_DRC)
compParm(Past_T3_DRC, 'ed50')
compParm(Past_T3_DRC, 'ed50', "-")
plot(Past_T3_DRC)

Past_T3_ED <- ED(Past_T3_DRC, c(50), interval = "delta")

Past_T3_ED_df <- as.data.frame(Past_T3_ED) %>%
  setDT(keep.rownames = "Geno") %>%
  mutate(Genotype = case_when(grepl(":01", Geno) ~ "01",
                              grepl(":02", Geno) ~ "02",
                              grepl(":03", Geno) ~ "03",
                              grepl(":04", Geno) ~ "04",
                              grepl(":05", Geno) ~ "05",
                              grepl(":06", Geno) ~ "06",
                              grepl(":07", Geno) ~ "07",
                              grepl(":08", Geno) ~ "08",
                              grepl(":09", Geno) ~ "09",
                              grepl(":10", Geno) ~ "10")) %>%
  mutate(TP_ID = case_when(grepl("T3", Geno)~ "T3",
                           grepl("T4", Geno)~ "T4",
                           grepl("T5", Geno)~ "T5")) %>%
select(-Geno, ED50 = Estimate) %>%
  mutate(site = case_when(Genotype == "01" | Genotype == "02" | Genotype == "03" | 
                            Genotype == "04" | Genotype == "05" ~ "offshore",
                          Genotype == "06" | Genotype == "07" | Genotype == "08" | 
                            Genotype == "09" | Genotype == "10" ~ "inshore"))

Past_ED50_T3 <- Past_T3_ED_df %>%
  select(Genotype, TP_ID, site, ED50) %>%
  filter(ED50 < 50) # Geno 08 T4 sample is very high 

Genotype_T3 <- Past_ED50_T3$Genotype

ggplot(Past_ED50_T3, aes(x = TP_ID, y = ED50, color = Genotype)) +
  geom_point() +
  ggrepel::geom_text_repel(label= Genotype_T3, nudge_x = 0.25) +
  facet_wrap(~site) +
  theme_bw() +
  theme(legend.position = "none") 

ggsave(filename = "plots/Past_Rank_ED50_all_TP_genofits.png", width = 174, height = 100, units = "mm")

  
geno_ED50s_T3 <- Past_ED50_T3 %>%
  spread(key = TP_ID, value = ED50) %>%
  group_by(Genotype) %>%
  mutate(avgfit = mean(c(T3, T4, T5)),
         min = min(c(T3, T4, T5)),
         max = max(c(T3, T4, T5)),
         diff = max - min) 

library("writexl")
geno_ED50s_T3 %>%
  write_xlsx("ED50/Past_T3_Genets_ED50.xlsx")


```
































# SANDBOXING AND RANDOM REFERENCE CODE CHUNKS #

```{r}
Acer_T3 <- Allpam %>%
  filter(species == "ACER") %>%
  filter(TP_ID == "T3")

str(Acer_T3)

ACER_DRC <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$species=="ACER",], curveid=Geno, fct = LL.3())
summary(ACER_DRC)
plot(ACER_DRC)

#Run whole population/species instead, pooling all Fv/Fm values across genotypes
ACER_DRC1 <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$species=="ACER",], fct = LL.3())

#extract mean ED50 for the population and compute 95% CIs
ACER_coeff<-data.frame(ED(ACER_DRC1, c(50)))
ACER_coeff_mean<-ACER_coeff[,1]
ACER_coeff_lower<-ACER_coeff[,1] - 1.96*ACER_coeff[,2]
ACER_coeff_upper<-ACER_coeff[,1] + 1.96*ACER_coeff[,2]

Coeff_means<-data.frame(ACER_coeff_mean)
Coeff_lowers<-data.frame(ACER_coeff_lower)
Coeff_uppers<-data.frame(ACER_coeff_upper)

ACER_preddata = data.frame(temp = seq(30,37, length.out = 100))
ACER_pred = as.data.frame(predict(ACER_DRC1, newdata = ACER_preddata, interval = 'confidence'))
ACER_preddata = data.frame(ACER_preddata, fvfm = ACER_pred$Prediction, Lower = ACER_pred$Lower, Upper = ACER_pred$Upper)


ggplot() +
  geom_jitter(data = Acer_T3, aes(x = Temperature, y = FvFm, color = species), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(29,40), breaks=c(30,32,34,36,38)) +
  scale_y_continuous(limits=c(-0.01, 0.75), breaks=c(0, 0.2, 0.4, 0.6)) +
  
  geom_line(data = ACER_preddata, aes(x = temp, y = fvfm), color = 'royalblue2', show.legend = FALSE) +
  geom_ribbon(data = ACER_preddata, aes(x = temp, ymin=Lower, ymax=Upper), color = 'royalblue2', linetype=2, alpha = 
                0.2) +
  geom_vline(data = Coeff_means, aes(xintercept = ACER_coeff_mean), color = 'royalblue2', show.legend = FALSE) +
  annotate("rect", xmin=Coeff_lowers$ACER_coeff_lower, xmax=Coeff_uppers$ACER_coeff_upper, ymin=-Inf, ymax=Inf, fill= 'royalblue2',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=round(ACER_coeff_mean, digits = 2)), x = 31, y = 0.3, show.legend = FALSE, 
            color = 'royalblue2') +
  ggtitle("Fv/Fm ED50 thermal thresholds") +
  scale_color_manual(values=c("royalblue2", "darkgoldenrod1", "darkorange1", "red3", "springgreen1", "purple3")) +
  ylab("Fv/Fm") +
  xlab("Temperature (Â°C)") +
  theme_bw()





ACER_DRC <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$species=="ACER",], curveid=Geno, fct = LL.3())
summary(ACER_DRC)
plot(ACER_DRC)

#extract mean ED50 for the population and compute 95% CIs
ACER_coeff<-data.frame(ED(ACER_DRC, c(50)))
ACER_coeff_mean<-ACER_coeff[,1]
ACER_coeff_lower<-ACER_coeff[,1] - 1.96*ACER_coeff[,2]
ACER_coeff_upper<-ACER_coeff[,1] + 1.96*ACER_coeff[,2]

Coeff_means<-data.frame(ACER_coeff_mean)
Coeff_lowers<-data.frame(ACER_coeff_lower)
Coeff_uppers<-data.frame(ACER_coeff_upper)

ACER_preddata = data.frame(temp = seq(30,37, length.out = 100))
ACER_pred = as.data.frame(predict(ACER_DRC, newdata = ACER_preddata, interval = 'confidence'))
ACER_preddata = data.frame(ACER_preddata, fvfm = ACER_pred$Prediction, Lower = ACER_pred$Lower, Upper = ACER_pred$Upper)


ggplot() +
  geom_jitter(data = Acer_T3, aes(x = Temperature, y = FvFm, color = Geno), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(29,37.5), breaks=c(30,33,35,37)) +
  scale_y_continuous(limits=c(-0.01, 0.75), breaks=c(0, 0.2, 0.4, 0.6)) +

  geom_line(data = ACER_preddata, aes(x = temp, y = fvfm), color = 'royalblue2', show.legend = FALSE) +
  geom_ribbon(data = ACER_preddata, aes(x = temp, ymin=Lower, ymax=Upper), color = 'royalblue2', linetype=2, alpha = 
                0.2) +
  geom_vline(data = Coeff_means, aes(xintercept = ACER_coeff_mean), color = 'royalblue2', show.legend = FALSE) +
  annotate("rect", xmin=Coeff_lowers$ACER_coeff_lower, xmax=Coeff_uppers$ACER_coeff_upper, ymin=-Inf, ymax=Inf, fill= 'royalblue2',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=round(ACER_coeff_mean, digits = 2)), x = 31, y = 0.3, show.legend = FALSE, 
            color = 'royalblue2') +
  ggtitle("Fv/Fm ED50 thermal thresholds") +
  ylab("Fv/Fm") +
  xlab("Temperature (°C)") +
  theme_bw()


  # scale_color_manual(values=c("royalblue2", "darkgoldenrod1", "darkorange1", "red3", "springgreen1", "purple3")




```



```{r}
Acer_T3 <- Allpam %>%
  filter(species == "ACER") %>%
  filter(TP_ID == "T3")


#### Generate curves and ED50s ####
ACER_DRC <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$species=="ACER",], curveid=Geno, fct = LL.3())
summary(ACER_DRC)
plot(ACER_DRC)

CBASS <- drm(FvFm ~ Temperature, data = Acer_T3, fct = LL.3())
summary(CBASS)
plot(CBASS)

AC07drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="07",], fct = LL.3())
summary(AC07drc)
plot(AC07drc)

AC31drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="31.0",], fct = LL.3())
summary(AC31drc)
plot(AC31drc)

AC34drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="34.0",], fct = LL.3())
summary(AC34drc)
plot(AC34drc)

AC41drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="41.0",], fct = LL.3())
summary(AC41drc)
plot(AC41drc)

AC48drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="48.0",], fct = LL.3())
summary(AC48drc)
plot(AC48drc)

AC50drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="50.0",], fct = LL.3())
summary(AC50drc)
plot(AC50drc)

AC62drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="62.0",], fct = LL.3())
summary(AC62drc)
plot(AC62drc)

ACCM5drc <- drm(FvFm ~ Temperature, data = Acer_T3[Acer_T3$Geno=="CM5",], fct = LL.3())
summary(ACCM5drc)
plot(ACCM5drc)

############################################################################################
#### Combine ED50 data plus predict curves from models for plotting ####
###########################################################################################
#overall DRC predictors

CBASS_preddata = data.frame(Temp = seq(30,37, length.out = 100))
CBASS_pred = as.data.frame(predict(CBASS, newdata = CBASS_preddata, interval = 'confidence'))
CBASS_preddata = data.frame(CBASS_preddata, Y = CBASS_pred$Prediction, Lower = CBASS_pred$Lower, Upper = CBASS_pred$Upper)

#genotype predictors
AC07_pred = as.data.frame(predict(AC07drc, newdata = CBASS_preddata, interval = 'confidence'))
AC07_preddata = data.frame(CBASS_preddata, Y = AC07_pred$Prediction, Lower = AC07_pred$Lower, Upper = AC07_pred$Upper)

AC31_pred = as.data.frame(predict(AC31drc, newdata = CBASS_preddata, interval = 'confidence'))
AC31_preddata = data.frame(CBASS_preddata, Y = AC31_pred$Prediction, Lower = AC31_pred$Lower, Upper = AC31_pred$Upper)

AC34_pred = as.data.frame(predict(AC34drc, newdata = CBASS_preddata, interval = 'confidence'))
AC34_preddata = data.frame(CBASS_preddata, Y = AC34_pred$Prediction, Lower = AC34_pred$Lower, Upper = AC34_pred$Upper)

AC41_pred = as.data.frame(predict(AC41drc, newdata = CBASS_preddata, interval = 'confidence'))
AC41_preddata = data.frame(CBASS_preddata, Y = AC41_pred$Prediction, Lower = AC41_pred$Lower, Upper = AC41_pred$Upper)

AC48_pred = as.data.frame(predict(AC48drc, newdata = CBASS_preddata, interval = 'confidence'))
AC48_preddata = data.frame(CBASS_preddata, Y = AC48_pred$Prediction, Lower = AC48_pred$Lower, Upper = AC48_pred$Upper)

AC50_pred = as.data.frame(predict(AC50drc, newdata = CBASS_preddata, interval = 'confidence'))
AC50_preddata = data.frame(CBASS_preddata, Y = AC50_pred$Prediction, Lower = AC50_pred$Lower, Upper = AC50_pred$Upper)

AC62_pred = as.data.frame(predict(AC62drc, newdata = CBASS_preddata, interval = 'confidence'))
AC62_preddata = data.frame(CBASS_preddata, Y = AC62_pred$Prediction, Lower = AC62_pred$Lower, Upper = AC62_pred$Upper)

ACCM5_pred = as.data.frame(predict(ACCM5drc, newdata = CBASS_preddata, interval = 'confidence'))
ACCM5_preddata = data.frame(CBASS_preddata, Y = ACCM5_pred$Prediction, Lower = ACCM5_pred$Lower, Upper = ACCM5_pred$Upper)

geno_coeff<-ACER_DRC$coefficients[21:30]
coeffs<-data.frame(geno_coeff)
coeffs[,'geno_coeff']=round(coeffs[,'geno_coeff'],2)


# ALL GENO FIGURE #
ggplot() +
  geom_jitter(data = Acer_T3, aes(x = Temperature, y = FvFm, color=Geno), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(29,38), breaks=c(29,31,33,35,37)) +
  scale_y_continuous(limits=c(-0.1, 0.7), breaks=c(0, 0.2, 0.4, 0.6)) +
  
geom_line(data = AC07_preddata, aes(x = Temp, y = Y), color = 'royalblue2', show.legend = FALSE) +
  geom_vline(data = AC07drc, aes(xintercept = Coefficients), color = 'royalblue2', show.legend = FALSE) 

+
  annotate("rect", xmin=Coeff_lowers$ACER_coeff_lower, xmax=Coeff_uppers$ACER_coeff_upper, ymin=-Inf, ymax=Inf, 
           fill= 'royalblue2',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=round(ACER_coeff_mean, digits = 2)), x = 31, y = 0.3, show.legend =
              FALSE, color = 'royalblue2') 
  
  
  
  
  
  
  
  
  geom_line(data = AC31_preddata, aes(x = Temp, y = Y), color = 'royalblue2', show.legend = FALSE) +
  geom_vline(data = Coeff_means, aes(xintercept = ACER_coeff_mean), color = 'royalblue2', show.legend = FALSE) +
  annotate("rect", xmin=Coeff_lowers$ACER_coeff_lower, xmax=Coeff_uppers$ACER_coeff_upper, ymin=-Inf, ymax=Inf, 
           fill= 'royalblue2',  alpha = 0.1) +
  geom_text(data = Coeff_means, aes(label=round(ACER_coeff_mean, digits = 2)), x = 31, y = 0.3, show.legend =
              FALSE, color = 'royalblue2') 
  


























































#### PLOT  DRC for experiment####
DRC_plot<- ggplot() +
  geom_jitter(data = Acer_T3, aes(x = Temperature, y = FvFm), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(26,38), breaks=c(27,29,31,33,35,37)) +
  scale_y_continuous(limits=c(-0.1, 0.7), breaks=c(0, 0.2, 0.4, 0.6)) +

  geom_line(data = CBASS_preddata, aes(x = Temp, y = Y), color = 'blue3', show.legend = FALSE) +
  geom_ribbon(data = CBASS_preddata, aes(x = Temp, ymin=Lower, ymax=Upper), color = 'blue3', linetype=2, alpha = 0.2) +
  geom_vline(aes(xintercept = 34.45), color = 'blue3', show.legend = FALSE) +
  geom_text(aes(label = '34.45', x = 35.2, y = 0.6), color='blue') +
  
  ylab("Fv/Fm") +
  xlab("Temperature (Â°C)") +
  theme_classic()


#### PLOT  DRC for each geno####
DRC_plot<- ggplot() +
  geom_jitter(data = Acer_T3, aes(x = Temperature, y = FvFm, color=Geno), size = 1, width = 0.25) +
  scale_x_continuous(limits=c(26,38), breaks=c(27,29,31,33,35,37)) +
  scale_y_continuous(limits=c(-0.1, 0.7), breaks=c(0, 0.2, 0.4, 0.6)) +
  scale_color_manual(values=c("AC31" = "red3", "AC41" = "darkorange2", "AC50" = "yellow2","AC62" = "royalblue", "AC7" = "navyblue", 
                              "CU12" = "forestgreen", "CU19" = "green3", "CU70" = "purple", "CU76" = "mediumpurple", "CU80" = "hotpink")) +
  
  geom_line(data = AC31_preddata, aes(x = Temp, y = Y), color = 'red3', show.legend = FALSE) +
  geom_vline(data = ACER_coeff, aes(xintercept = ACER_coeff[1]), color = 'red3', show.legend = FALSE) +
  geom_text(data = ACER_coeff, aes(label = "AC31: 34.08"), x = 37, y = 0.67, show.legend = FALSE, color = 'red3') +
  


  
    ylab("Fv/Fm") +
  xlab("Temperature (Â°C)") +
  theme_classic()



```
























































































# PORITES #
```{r}
PAST <- Allpam %>%
  filter(species == "PAST")

Past_TP <-  PAST %>%
  filter(TubeNumber != "NA") %>%
  select(Geno, Treatment, Temp, TP_ID, FvFm) %>%
  filter(Treatment != "Field", 
         Treatment != "Initial")

ggplot(Past_TP, aes(x = TP_ID, y = FvFm, color = Geno)) +
  geom_point() +
  facet_wrap(~Treatment)

Past_TP$Treatment_f = factor(Past_TP$Treatment, levels=c('Control','Low','Medium','High'))

ggplot(Past_TP, aes(x = TP_ID, y = FvFm, color = Geno)) +
  geom_point() +
  facet_grid(Geno~Treatment_f) +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("Timepoint")

ggsave(filename = "plots/Past_FvFm_Treatment_TP.png", width = 300, height = 250, units = "mm")

x <- Past_TP %>%
  filter(Geno == "06")

DRCpamgeno = drm(FvFm ~ Temp, data = x, curveid = TP_ID,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)

ggplot(x, aes(x = Temp, y = FvFm, color = TP_ID)) +
  geom_line()

```

```{r}
Past_T5 <- PAST %>%
  filter(TubeNumber != "NA") %>%
  filter(TP_ID == "T5") %>%
  select(sample_ID, Geno, Treatment, Temp, Timepoint, FvFm)

Past_T5_PAM <- PAST %>%
  filter(TubeNumber == "NA",
         TP_ID == "T5") %>%
  select(sample_ID, Geno, Treatment, Temp, Timepoint, FvFm)

a <- rbind(Past_T5, Past_T5_PAM)

ggplot(a, aes(x = Temp, y = FvFm)) +
  geom_point() +
  facet_grid(Timepoint~Geno)


ggplot(Past, aes(x = Temp, y = FvFm, color = Geno)) +
  geom_point() +
  facet_grid(~Geno) +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("Timepoint")
```

# T1 #
```{r}
T1 <- PAST %>%
  filter(TP_ID == "T1")

DRCpamgeno = drm(FvFm ~ Temp, data = T1, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)

T1_ED <- ED(DRCpamgeno, c(50), interval = "delta")

T1_df<- as.data.frame(T1_ED) 

T1_ED50 <- setDT(T1_df, keep.rownames = "Geno") %>%
  mutate(Genotype = case_when(grepl(":01", Geno) ~ "01",
                              grepl(":02", Geno) ~ "02",
                              grepl(":03", Geno) ~ "03",
                              grepl(":04", Geno) ~ "04",
                              grepl(":05", Geno) ~ "05",
                              grepl(":06", Geno) ~ "06",
                              grepl(":07", Geno) ~ "07",
                              grepl(":08", Geno) ~ "08",
                              grepl(":09", Geno) ~ "09",
                              grepl(":10", Geno) ~ "10"))
T1_ED50_geno <- T1_ED50 %>%
  select(Genotype, ED50 = Estimate)




```




```{r}
T1 <- PAST %>%
  filter(TP_ID == "T1") %>%
  select(Geno, FvFm, Temp)


demo.LL.3 <- drm(FvFm ~ Temp, data = T1, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))

demo.fits <- expand.grid(conc=exp(seq(log(1.00e-04), log(1.00e-09), length=100)))

pm <- predict(demo.LL.3, newdata=demo.fits, interval="confidence") 
    demo.fits$p <- pm[,1]
    demo.fits$pmin <- pm[,2]
    demo.fits$pmax <- pm[,3]


demo1$XX <- demo1$X
demo1$XX[demo1$XX == 0] <- 1.00e-09

ggplot(demo1, aes(x = variable, y = value)) +
  geom_point() +
  geom_ribbon(data=demo.fits, aes(x=conc, y=p, ymin=pmin, ymax=pmax), alpha=0.2) +
  geom_line(data=demo.fits, aes(x=conc, y=p)) +
  coord_trans(x="log") 





```















```{r}

Allpam$Temp <- as.character(Allpam$Temp)

ggplot(Allpam, aes(x = Temp, y =FvFm)) +
 geom_violin() 
  

  

```





















# Dose-response curve model fitting
```{r model, results = 'hide'}
# Select whether to use target temp or actual recorded max temp for model fitting
df <- if (temp.adjust) {
  df %>% select(-target_temp)
} else {
  df %>% mutate(max_temp = target_temp) %>% select(-target_temp)
}

# Define function to fit 3-parameter LL model to data and return NULL if fitting error
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(120, 0.72, 40),
      lowerl = c(10, 0.55, 30))}
tryll3 <- possibly(ll3, otherwise = NULL)

# Fit model to each coral, get parameters, fitted values, and residuals
initmods <- df %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- initmods %>% 
  select(nursery, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and diagnostics
vals <- initmods %>%
  select(nursery, geno, pred) %>%
  unnest(pred) %>%
  full_join(ed50) %>%
  full_join(df) %>%
  rename(ed50 = estimate)

# Identify problematic data points based on cook's distance and residuals
counts <- vals %>% 
  group_by(nursery, geno) %>% 
  summarise(n = sum(!is.na(fvfm)))
dff <- vals %>%
  left_join(counts) %>%
  group_by(nursery, geno) %>%
  mutate(resid.thresh = 2*sd(.resid, na.rm = T)) %>%  # Calculate residual threshold as 2 standard deviations
  mutate(cooksd.thresh = 4/n) %>%   # Calculate cook's distance threshold as 4/n
  mutate(max_to_remove = floor(n * 0.2)) %>%
  ungroup() %>%
  mutate(problem = case_when(.cooksd > cooksd.thresh & .resid > 0 ~ "high cook's distance",
                             .resid > resid.thresh ~ "high residual", 
                             TRUE ~ problem)) %>%
  group_by(nursery, geno, outlier = problem %in% c("high cook's distance", "high residual")) %>%
  mutate(n.outliers = n(),
         rank.out = order(.cooksd, decreasing = TRUE)) %>%
  ungroup() %>%
  mutate(fvfm = case_when(outlier & rank.out <= max_to_remove ~ NA_real_, 
                          TRUE ~ fvfm)) 


# Refit models without problematic points
fmods <- dff %>%
  select(nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm) %>%
  nest(data = c(max_temp, f, fm, fvfmraw, fvfm, problem)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, tryll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
fed50 <- fmods %>% 
  select(nursery, geno, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")

# Collect raw data, fitted values, and ed50 estimates
fvals <- fmods %>%
  select(nursery, geno, pred) %>%
  unnest(pred) %>%
  full_join(fed50) %>%
  full_join(select(dff, nursery, geno, max_temp, f, fm, fvfmraw, problem, fvfm)) %>%
  rename(ed50 = estimate)
```











```{r}

str(Full_PAM)

ACER_DRC <- drm(FvFm ~ Temperature, data = Full_PAM[Full_PAM$species=="ACER",], curveid=sample_ID, fct = LL.3())


summary(ACER_DRC)
plot(ACER_DRC)
```

























# IMPORT DATA #
```{r}


Full_PAM$species<-as.factor(Full_PAM$species)
Full_PAM$Timepoint<-as.factor(Full_PAM$Timepoint)
Full_PAM$Genotype<-as.factor(Full_PAM$Genotype)
Full_PAM$Location<-as.factor(Full_PAM$Location)
Full_PAM$Temperature<-as.numeric(Full_PAM$Temperature)
Full_PAM$sample_ID<-as.factor(Full_PAM$sample_ID)


# Inshore Past
InshorePa <-read.delim("data/PAM/2021-06-08_CarlysInshore_Past_RNASeq.txt")

IPa <- InshorePa %>%
  gather(key = "Tp", value = FvFm, -SampleName, -species, -Tank, -Temp, -Geno, -Timepoint) %>%
  filter(!is.na(FvFm)) %>%
  select(species, sample_ID = SampleName, Tank, Temperature = Temp, Timepoint, FvFm) %>%
  mutate(replicate = case_when(Tank == 1 ~ "C",
                               Tank == 2 ~ "L",
                               Tank == 3 ~ "M",
                               Tank == 4 ~ "H"))
# Offshore Past 
OffshorePa <- read.delim("data/PAM/2021-06-10_CarlysOffshore_Past_RNASeq.txt") %>%
  select(-Start.EndTimes, -X, -X.1, -Tank.1, -Time.on.Spec, -Record, -PAR)





```

