---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LOAD LIBRARIES #
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
```

#IMPORT DATA#
```{r}
# Import Raw Nanodrop Data and Designate Extraction Origin#
df <- readxl::read_xlsx("data/Nanodrop/Past_Nano_Working_Master.xlsx") %>%
  mutate(origin = ifelse(grepl("F", Sample_ID), "Flash Frozen", "RNALater")) %>%
  mutate(origin = ifelse(grepl("r", Sample_ID), "Re-extraction", origin))

# no letter = original sample extracted from RNALater
# F = number coincides with the RNALater sample #, but came from the Flash Frozen tissue
# r = re-extraction of original sample from RNALater 

#remove lettering system for easier sample analysis downstream, sample origin is denoted in "origin" column #
df$Sample_ID<-gsub("F","",as.character(df$Sample_ID))
df$Sample_ID<-gsub("r","",as.character(df$Sample_ID))


# Import Additional Sample Data #
sd <- readxl::read_xlsx("data/Nanodrop/Past_Sample_Data.xlsx") %>%
  mutate(TP = case_when(grepl("TF", FrozenSampleName) ~ "TF",
                        grepl("T0", FrozenSampleName) ~ "T0",
                        grepl("T1", FrozenSampleName) ~ "T1",
                        grepl("T2", FrozenSampleName) ~ "T2",
                        grepl("T3", FrozenSampleName) ~ "T3",
                        grepl("T4", FrozenSampleName) ~ "T4",
                        grepl("T5", FrozenSampleName) ~ "T5")) %>%
  mutate(Temperature = case_when(grepl("-C", FrozenSampleName) ~ "Control",
                               grepl("-L", FrozenSampleName) ~ "Low",
                               grepl("-M", FrozenSampleName) ~ "Medium",
                               grepl("-H", FrozenSampleName) ~ "High"))


sd$Sample_ID <- as.character(sd$Sample_ID)

# Combine Nanodata with Sample Data #
nano <- right_join(df, sd, by = "Sample_ID") %>%
  select(FrozenSampleName, Sample_ID, origin,  Site, Date, ng_ul, r260_280, r260_230,  TP, Temperature) %>%
  filter(!is.na(Date)) 

# Convert Character Columns to Numeric #
nano$ng_ul <- as.numeric(nano$ng_ul)
nano$r260_280 <- as.numeric(nano$r260_280)
nano$r260_230 <- as.numeric(nano$r260_230)

# Round values to 2 decimal places #
nano$ng_ul <- round(nano$ng_ul, digits = 2)
nano$r260_280  <- round(nano$r260_280 , digits = 2)
nano$r260_230 <- round(nano$r260_230, digits = 2)
```

#FILTERING GOOD AND BAD SAMPLES FROM ORIGINAL EXTRACTIONS#
```{r}
ogextract <- nano %>%
  filter(origin == "RNALater")

# RNA Samples >= 20ng/uL #
goodRNA <- ogextract %>%
  filter(ng_ul >= 18.5)

# RNA Samples with low yields, < 20ng/uL but > 10ng/uL #
lowyield <- ogextract %>%
  filter(ng_ul < 18.5, ng_ul > 10)

# RNA Samples with little to no RNA (< 10ng/uL) # 
noRNA <- ogextract %>%
  filter(ng_ul < 10)

```

#VISUALIZING DATA#
```{r}
# Boxplot: all samples separated by timepoint
ggplot(nano, aes(x = TP, y = ng_ul, fill = TP)) +
  geom_boxplot() +
  geom_hline(yintercept=18.5, color = "red", size = 0.5) 

# Boxplot: samples <20ng/uL by timepoint
ggplot(lowyield, aes(x = TP, y = ng_ul, fill = TP)) +
  geom_boxplot() +
  geom_hline(yintercept=18.5, color = "red", size = 0.5)

# Scatterplot: All data, Sample ng/uL of RNA for each sample, faceted by timepoint 
ggplot(nano, aes(x = Sample_ID, y = ng_ul, color = TP)) +
  geom_point() +
  geom_hline(yintercept=18.5, color = "red", size = 0.5) +
  facet_wrap(~TP, scales = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_blank())

# Scatterplot: Bad samples, Sample ng/uL of RNA for each sample, faceted by timepoint 
ggplot(notgoodRNA, aes(x = Sample_ID, y = ng_ul, color = TP)) +
  geom_point(size = 2) +
  geom_hline(yintercept=20, color = "red", size = 0.5) +
  facet_wrap(~TP, scales = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_blank())

# Scatterplot: All data, Sample ng/uL of RNA for each sample, faceted by timepoint 
ggplot(nano, aes(x = Sample_ID, y = ng_ul, color = TP)) +
  geom_point() +
  geom_hline(yintercept=20, color = "red", size = 0.5) +
  facet_grid(Site~TP, scales = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_blank())

# Scatterplot: All data, Sample ng/uL of RNA for each sample, faceted by Date
ggplot(nano, aes(x = Sample_ID, y = ng_ul, color = TP)) +
  geom_point(size = 2) +
  geom_hline(yintercept=20, color = "red", size = 0.5) +
  facet_wrap( ~ as.Date(Date), scales = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_blank())

# Scatterplot: All data, Sample ng/uL of RNA for each sample, faceted by Tank Temperature 
ggplot(nano, aes(x = Sample_ID, y = ng_ul, color = TP)) +
  geom_point(size = 2) +
  geom_hline(yintercept=20, color = "red", size = 0.5) +
  facet_wrap( ~ Temperature, scales = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_blank())

```

# QUANTIFYING GOOD AND BAD SAMPLES BY TIMEPOINT #
```{r}
x <- nano %>%
  select(Sample_ID, ng_ul, r260_280, r260_230, TP) %>%
  mutate(status = case_when(ng_ul >= 18.5 ~ "good",
                            ng_ul > 10 & ng_ul < 18.5 ~ "lowyield",
                            ng_ul < 10 ~ "noRNA")) %>%
  filter(Sample_ID != 321) %>%
  group_by(status, TP) %>%d
  summarise(n = n()) %>%
  mutate(ncol = sum(n), label = paste0("N =", n))


ggplot(x, aes(x = status, y = n, fill = status)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_fill_manual(values = c("Green3", "Yellow2", "Red2")) +
  geom_text(aes(label = label, y = 1)) +
  scale_y_discrete(expand = c(0,0)) +
  facet_wrap(~TP) +
  theme_bw()

```








#vISUALIZING DATA FROM DIFFERENT HOMOGENIZATION PROTOCOL#
```{r}
flash_frozen <- df %>%
  filter(Sample_ID == "4F"|Sample_ID == "5F"|Sample_ID == "6F"|Sample_ID == "7F"|Sample_ID == "8F"|
           Sample_ID == "9F") %>%
  mutate(Tissue = "Flash_Frozen")

ggplot(flash_)
  

RNALater <- df %>%
  filter(Sample_ID == "4"|Sample_ID == "5"|Sample_ID == "6"|Sample_ID == "7"|Sample_ID == "8"|Sample_ID == "9") %>%
  mutate(Tissue = "RNALater") 

Tissue <- rbind(flash_frozen, RNALater)%>% 
  select(-Time) 

ggplot(Tissue, aes(x = Sample_ID, y = ng_ul, color = Tissue)) +
  geom_point(size = 2)





```

