---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LOAD LIBRARIES #
```{r}
library(Hmisc)
library(lsmeans)
library(emmeans)
library(car)
library(drc)
library(tidyverse)
```

# IMPORT DATA #
```{r}
MAc <- readxl::read_xlsx("data/PAM/2021-06-11_Acer-4temps-MoteLooeNursery_Run2.xlsx")

Allpam <- MAc %>%
  mutate(Species = case_when(Species == "Acropora cervicornis" ~ "ACER")) %>%
  select(sample_ID = SampleName, species = Species, Geno = Genotype, Location, Temp = Temp_Setpoint, Timepoint, FvFm = PAM) %>%
  mutate(TP_ID = case_when(grepl("T1", sample_ID) ~ "T1",
                           grepl("T2", sample_ID) ~ "T2",
                           grepl("T3", sample_ID) ~ "T3",
                           grepl("T4", sample_ID) ~ "T4",
                           grepl("T5", sample_ID) ~ "T5",
                           grepl("T0", sample_ID) ~ "T0",
                           grepl("TF", sample_ID) ~ "TF"))


Allpam$FacTemp<-as.factor(Allpam$Temp)
Allpam$Geno<-as.factor(Allpam$Geno)
Allpam$Temp<- as.integer(Allpam$Temp)
Allpam<-as.data.frame(Allpam)
```

# T3 ANALYSIS (T3 & T4 & T5 Samples) #
```{r}
T3PAM <- Allpam %>%
  filter(Timepoint == "T3")

aggregate(FvFm ~ Temp, data=T3PAM, summary)

aggregate(FvFm ~ Temp, data=T3PAM, length)

# Homoscedasticity/ Equal Variance Testing 
bartlett.test(FvFm ~ FacTemp, data=T3PAM)
leveneTest(FvFm ~ FacTemp, data=T3PAM)
aggregate(FvFm ~ FacTemp, data=T3PAM, FUN= function(x) shapiro.test(x)$p.value)

n1<-aov(FvFm ~ FacTemp + Error(Geno/FacTemp), T3PAM)
summary(n1)

print(lsmeans(n1, list(pairwise ~ FacTemp)), adjust = c("tukey"))


# Full Curve Fit 
DRCpam = drm(FvFm ~ Temp, data = T3PAM,
                 fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpam)
plot(DRCpam)

DRCpamgeno = drm(FvFm ~ Temp, data = T3PAM, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)
ED(DRCpamgeno, c(50))[,1]

# Plotting 

# Population Average 
temp_x<- seq(30, 40.5, length = 100)

pdf("plots/2021-06-11_MoteLooeNursery_AcerRNASeq_DRC.pdf",10,7)
line_width=2
Colorz="blue"
Syms=16
Denscity <- 45
matplot(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
        type="n",col=Colorz,lty=c(1,3,3),lwd=line_width,ylab="Fv/Fm",xlab="Temperature °C", xlim=c(29.5,41),ylim=c(0,0.65), cex.axis=1.5, cex.lab=1.5)
polygon(c(temp_x, rev(temp_x)),c(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,2],rev(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,3])), col=Colorz, density = Denscity)
matpoints(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
          type="l",col=Colorz,lty=c(1,3,3),lwd=line_width)
with(T3PAM,matpoints(Temp,T3PAM,pch=Syms, col=Colorz, cex=1.5))

title(main="Mote Looe Nursery Acropora cervicornis")
abline(v=mean(ED(DRCpamgeno, c(50))[,1]), col=Colorz)
text(mean(ED(DRCpamgeno, c(50))[,1])+0.6, 0.65,labels=as.character(round(mean(ED(DRCpamgeno, c(50))[,1]), digits=2)),col=Colorz, cex=1.5)
dev.off()

# Individual Genotypes
pdf("plots/2021-06-11_MoteLooeNursery_AcerRNASeq_DRC_genofits.pdf",10,7)
par(mar=c(5.1,5.1,4.1,2.1))
Line_width=2.5
with(T3PAM, plot(Temp,FvFm,xlim=c(29.5,39.5),ylim=c(0,0.60), type='n', cex.axis=2.5, cex.lab=2.5, ylab="Fv/Fm", xlab="Temperature °C"))
Colours<-c('#4575b4','#74add1','#fee090','#f46d43','#d73027')
for(i in order(DRCpamgeno$coefficients[17:24])){
  Geno=names(table(T3PAM$Geno))[i]
  print(Geno)
  print(summary(mod1<-drm(FvFm ~ Temp, data=T3PAM[T3PAM$Geno==Geno,],fct = LL.3(names = c('hill', 'max', 'ed50')))))
  points(T3PAM[T3PAM$Geno==Geno,"Temp"],T3PAM[T3PAM$Geno==Geno,"FvFm"], col=Colours[i], pch=16)
  lines(temp_x, predict(mod1, data.frame(Temp = temp_x)), col=Colours[i], lwd=Line_width)
}
title(main="Mote Looe Nursery Acropora cervicornis")
abline(v=DRCpamgeno$coefficients[17:24][order(DRCpamgeno$coefficients[17:24])], col=Colours, lwd=Line_width)
legend("bottomleft", col=Colours, lty=1, cex=1.75, lwd=Line_width, paste0(names(DRCpamgeno$coefficients[17:24])[order(DRCpamgeno$coefficients[17:24])],": ",round(DRCpamgeno$coefficients[17:24][order(DRCpamgeno$coefficients[17:24])], digits=2)))
dev.off()

```
