---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LOAD LIBRARIES #
```{r}
library(Hmisc)
library(lsmeans)
library(emmeans)
library(car)
library(drc)
library(tidyverse)
```

# IMPORT DATA #
```{r}
IPa <- readxl::read_xlsx("data/PAM/2021-06-08_Past-4temps-Inshore.xlsx")

Allpam <- IPa %>%
  mutate(Species = case_when(Species == "Porites astreoides" ~ "PAST")) %>%
  select(sample_ID = SampleName, species = Species, Geno = Genotype, Location, Temp = Temp_Setpoint, Timepoint, FvFm = PAM) %>%
  filter(Timepoint != "TF",
         Timepoint != "T0")

Allpam$FacTemp<-as.factor(Allpam$Temp)
Allpam$Geno<-as.factor(Allpam$Geno)
Allpam$Temp<- as.integer(Allpam$Temp)

```

# T3 ANALYSIS #
```{r}
T3PAM <- Allpam %>%
  filter(Timepoint == "T3")

aggregate(FvFm ~ Temp, data=T3PAM, summary)

aggregate(FvFm ~ Temp, data=T3PAM, length)

# Homoscedasticity/ Equal Variance Testing 
bartlett.test(FvFm ~ FacTemp, data=T3PAM)
leveneTest(FvFm ~ FacTemp, data=T3PAM)
aggregate(FvFm ~ FacTemp, data=T3PAM, FUN= function(x) shapiro.test(x)$p.value)

n1<-aov(FvFm ~ FacTemp + Error(Geno/FacTemp), T3PAM)
summary(n1)

print(lsmeans(n1, list(pairwise ~ FacTemp)), adjust = c("tukey"))


# Full Curve Fit 
DRCpam = drm(FvFm ~ Temp, data = T3PAM,
                 fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpam)
plot(DRCpam)

DRCpamgeno = drm(FvFm ~ Temp, data = T3PAM, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)
ED(DRCpamgeno, c(50))[,1]

# Plotting 

# Population Average 
temp_x<- seq(30, 40.5, length = 100)

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC.pdf",10,7)
line_width=2
Colorz="blue"
Syms=16
Denscity <- 45
matplot(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
        type="n",col=Colorz,lty=c(1,3,3),lwd=line_width,ylab="Fv/Fm",xlab="Temperature °C", xlim=c(29.5,41),ylim=c(0,0.65), cex.axis=1.5, cex.lab=1.5)
polygon(c(temp_x, rev(temp_x)),c(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,2],rev(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,3])), col=Colorz, density = Denscity)
matpoints(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
          type="l",col=Colorz,lty=c(1,3,3),lwd=line_width)
with(T3PAM,matpoints(Temp,FvFm,pch=Syms, col=Colorz, cex=1.5))

title(main="Carly's Inshore Porites astreoides")
abline(v=mean(ED(DRCpamgeno, c(50))[,1]), col=Colorz)
text(mean(ED(DRCpamgeno, c(50))[,1])+0.6, 0.65,labels=as.character(round(mean(ED(DRCpamgeno, c(50))[,1]), digits=2)),col=Colorz, cex=1.5)
dev.off()

# Individual Genotypes

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC_genofits.pdf",10,7)
par(mar=c(5.1,5.1,4.1,2.1))
Line_width=2.5
with(T3PAM, plot(Temp,FvFm,xlim=c(29.5,41),ylim=c(0,0.60), type='n', cex.axis=2.5, cex.lab=2.5, ylab="Fv/Fm", xlab="Temperature °C"))
Colours<-c('#4575b4','#74add1','#fee090','#f46d43','#d73027')
for(i in order(DRCpamgeno$coefficients[11:15])){
  Geno=names(table(T3PAM$Geno))[i]
  print(Geno)
  print(summary(mod1<-drm(FvFm ~ Temp, data=T3PAM[T3PAM$Geno==Geno,],fct = LL.3(names = c('hill', 'max', 'ed50')))))
  points(T3PAM[T3PAM$Geno==Geno,"Temp"],T3PAM[T3PAM$Geno==Geno,"FvFm"], col=Colours[i], pch=16)
  lines(temp_x, predict(mod1, data.frame(Temp = temp_x)), col=Colours[i], lwd=Line_width)
}
abline(v=DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], col=Colours, lwd=Line_width)
legend("bottomleft", col=Colours, lty=1, cex=1.75, lwd=Line_width, paste0(names(DRCpamgeno$coefficients)[11:15][order(DRCpamgeno$coefficients[11:15])],": ",round(DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], digits=2)))
dev.off()
```





































# T3 ANALYSIS #
```{r}
Allpam<-read.delim("data/PAM/2021-06-08_CarlysInshore_Past_RNASeq.txt")


# Make Genotype and FacTemp factors 
Allpam$Geno<-as.factor(Allpam$Geno)
aggregate(T3PAM ~ Temp, data=Allpam, summary)

Allpam$FacTemp<-as.factor(Allpam$Temp)
aggregate(T3PAM ~ Temp, data=Allpam, length)

# Homoscedasticity/ Equal Variance Testing 
bartlett.test(T3PAM ~ FacTemp, data=Allpam)
leveneTest(T3PAM ~ FacTemp, data=Allpam)
aggregate(T3PAM ~ FacTemp, data=Allpam, FUN= function(x) shapiro.test(x)$p.value)

n1<-aov(T3PAM ~ FacTemp + Error(Geno/FacTemp), Allpam)
summary(n1)

print(lsmeans(n1, list(pairwise ~ FacTemp)), adjust = c("tukey"))

# Full Curve Fit 
DRCpam = drm(T3PAM ~ Temp, data = Allpam,
                 fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpam)
plot(DRCpam)

DRCpamgeno = drm(T3PAM ~ Temp, data = Allpam, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)
ED(DRCpamgeno, c(50))[,1]

# Plotting 

temp_x<- seq(30, 40.5, length = 100)

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC.pdf",10,7)
line_width=2
Colorz="blue"
Syms=16
Denscity <- 45
matplot(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
        type="n",col=Colorz,lty=c(1,3,3),lwd=line_width,ylab="Fv/Fm",xlab="Temperature °C", xlim=c(29.5,41),ylim=c(0,0.65), cex.axis=1.5, cex.lab=1.5)
polygon(c(temp_x, rev(temp_x)),c(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,2],rev(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,3])), col=Colorz, density = Denscity)
matpoints(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
          type="l",col=Colorz,lty=c(1,3,3),lwd=line_width)
with(Allpam,matpoints(Temp,T3PAM,pch=Syms, col=Colorz, cex=1.5))

title(main="Carly's Inshore Porites astreoides")
abline(v=mean(ED(DRCpamgeno, c(50))[,1]), col=Colorz)
text(mean(ED(DRCpamgeno, c(50))[,1])+0.6, 0.65,labels=as.character(round(mean(ED(DRCpamgeno, c(50))[,1]), digits=2)),col=Colorz, cex=1.5)
dev.off()

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC_genofits.pdf",10,7)
par(mar=c(5.1,5.1,4.1,2.1))
Line_width=2.5
with(Allpam, plot(Temp,T3PAM,xlim=c(29.5,41),ylim=c(0,0.60), type='n', cex.axis=2.5, cex.lab=2.5, ylab="Fv/Fm", xlab="Temperature °C"))
Colours<-c('#4575b4','#74add1','#fee090','#f46d43','#d73027')
for(i in order(DRCpamgeno$coefficients[11:15])){
  Geno=names(table(Allpam$Geno))[i]
  print(Geno)
  print(summary(mod1<-drm(T3PAM ~ Temp, data=Allpam[Allpam$Geno==Geno,],fct = LL.3(names = c('hill', 'max', 'ed50')))))
  points(Allpam[Allpam$Geno==Geno,"Temp"],Allpam[Allpam$Geno==Geno,"T3PAM"], col=Colours[i], pch=16)
  lines(temp_x, predict(mod1, data.frame(Temp = temp_x)), col=Colours[i], lwd=Line_width)
}
abline(v=DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], col=Colours, lwd=Line_width)
legend("bottomleft", col=Colours, lty=1, cex=1.75, lwd=Line_width, paste0(names(DRCpamgeno$coefficients)[11:15][order(DRCpamgeno$coefficients[11:15])],": ",round(DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], digits=2)))
dev.off()
```


# T4 ANALYSIS #
```{r}
# Make Genotype and FacTemp factors 
Allpam$Geno<-as.factor(Allpam$Geno)
aggregate(T4PAM ~ Temp, data=Allpam, summary)

Allpam$FacTemp<-as.factor(Allpam$Temp)
aggregate(T4PAM ~ Temp, data=Allpam, length)

# Homoscedasticity/ Equal Variance Testing 
bartlett.test(T4PAM ~ FacTemp, data=Allpam)
leveneTest(T4PAM ~ FacTemp, data=Allpam)
aggregate(T4PAM ~ FacTemp, data=Allpam, FUN= function(x) shapiro.test(x)$p.value)

n1<-aov(T4PAM ~ FacTemp + Error(Geno/FacTemp), Allpam)
summary(n1)

print(lsmeans(n1, list(pairwise ~ FacTemp)), adjust = c("tukey"))

# Full Curve Fit 
DRCpam = drm(T3PAM ~ Temp, data = Allpam,
                 fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpam)
plot(DRCpam)

DRCpamgeno = drm(T3PAM ~ Temp, data = Allpam, curveid = Geno,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)
ED(DRCpamgeno, c(50))[,1]

# Plotting 

temp_x<- seq(30, 40.5, length = 100)

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC.pdf",10,7)
line_width=2
Colorz="blue"
Syms=16
Denscity <- 45
matplot(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
        type="n",col=Colorz,lty=c(1,3,3),lwd=line_width,ylab="Fv/Fm",xlab="Temperature °C", xlim=c(29.5,41),ylim=c(0,0.65), cex.axis=1.5, cex.lab=1.5)
polygon(c(temp_x, rev(temp_x)),c(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,2],rev(predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence")[,3])), col=Colorz, density = Denscity)
matpoints(temp_x, predict(DRCpamgeno, data.frame(Temp = temp_x), interval="confidence"),
          type="l",col=Colorz,lty=c(1,3,3),lwd=line_width)
with(Allpam,matpoints(Temp,T3PAM,pch=Syms, col=Colorz, cex=1.5))

title(main="Carly's Inshore Porites astreoides")
abline(v=mean(ED(DRCpamgeno, c(50))[,1]), col=Colorz)
text(mean(ED(DRCpamgeno, c(50))[,1])+0.6, 0.65,labels=as.character(round(mean(ED(DRCpamgeno, c(50))[,1]), digits=2)),col=Colorz, cex=1.5)
dev.off()

pdf("plots/2021-06-08_T3_CarlysInshorePastRNASeq_DRC_genofits.pdf",10,7)
par(mar=c(5.1,5.1,4.1,2.1))
Line_width=2.5
with(Allpam, plot(Temp,T3PAM,xlim=c(29.5,41),ylim=c(0,0.60), type='n', cex.axis=2.5, cex.lab=2.5, ylab="Fv/Fm", xlab="Temperature °C"))
Colours<-c('#4575b4','#74add1','#fee090','#f46d43','#d73027')
for(i in order(DRCpamgeno$coefficients[11:15])){
  Geno=names(table(Allpam$Geno))[i]
  print(Geno)
  print(summary(mod1<-drm(T3PAM ~ Temp, data=Allpam[Allpam$Geno==Geno,],fct = LL.3(names = c('hill', 'max', 'ed50')))))
  points(Allpam[Allpam$Geno==Geno,"Temp"],Allpam[Allpam$Geno==Geno,"T3PAM"], col=Colours[i], pch=16)
  lines(temp_x, predict(mod1, data.frame(Temp = temp_x)), col=Colours[i], lwd=Line_width)
}
abline(v=DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], col=Colours, lwd=Line_width)
legend("bottomleft", col=Colours, lty=1, cex=1.75, lwd=Line_width, paste0(names(DRCpamgeno$coefficients)[11:15][order(DRCpamgeno$coefficients[11:15])],": ",round(DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], digits=2)))
dev.off()
```

















































# Testing Data Manip to calc ED50s
```{r}
library(lmerTest)
library(sjPlot)
library(Rmisc)
library(ggplot2)
library(reshape2)

Full_PAM <- Allpam %>%
  gather(key = "Tp", value = FvFm, -SampleName, -species, -Tank, -Temp, -Geno, -Timepoint, -FacTemp) %>%
  filter(!is.na(FvFm)) %>%
  select(species, sample_ID = SampleName, Tank, Temperature = Temp, Timepoint, FvFm) %>%
  mutate(replicate = case_when(Tank == 1 ~ "C",
                               Tank == 2 ~ "L",
                               Tank == 3 ~ "M",
                               Tank == 4 ~ "H"))

Full_PAM$species<-as.factor(Full_PAM$species)
Full_PAM$replicate<-as.factor(Full_PAM$replicate)
str(Full_PAM)

PAST_DRC <- drm(FvFm ~ Temperature, data = Full_PAM[Full_PAM$species=="Past",], curveid=sample_ID, fct = LL.3())
summary(PAST_DRC)
plot(PAST_DRC)




```




